// Mocks generated by Mockito from annotations
// in spacetime/test/app_tester.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:spacetime/upload.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DownloadManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadManager extends _i1.Mock implements _i2.DownloadManager {
  MockDownloadManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> saveFile({
    required String? name,
    required String? data,
    _i4.File? file,
    String? filePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveFile, [], {
              #name: name,
              #data: data,
              #file: file,
              #filePath: filePath,
            }),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#saveFile, [], {
                  #name: name,
                  #data: data,
                  #file: file,
                  #filePath: filePath,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<(String, String)> loadFile() =>
      (super.noSuchMethod(
            Invocation.method(#loadFile, []),
            returnValue: _i3.Future<(String, String)>.value((
              _i5.dummyValue<String>(this, Invocation.method(#loadFile, [])),
              _i5.dummyValue<String>(this, Invocation.method(#loadFile, [])),
            )),
          )
          as _i3.Future<(String, String)>);
}
