/* sortprof.c: sort profile data generated by java -prof. */


#include <stdlib.h>
#include <stdio.h>
#include <math.h>

struct times {
    int count;
    char callee[100];
    char caller[100];
    long time;
};
struct memory {
    char type[100];
    int count;
    int bytes;
};

int read_times(struct times *t)
{
    char s[150];
    int i,j;

    if( scanf("%[^\n]\n", s) != 1 ) return 0;
    if( s[0] == '#' ) return 0;
    sscanf(s,"%d", &(t->count));
    sscanf(s+84,"%d", &(t->time));
    i=0;
    for(j=9; j< 38+9; j++ )
    {
	t->callee[i] = s[j];
	if( s[j] != ' ' ) i++;
    }
    t->callee[i] = 0;
    for(i=0; j < 38+38+9; j++)
    {
	t->caller[i] = s[j];
	if( s[j] != ' ' ) i++;
    }
    t->caller[i] = 0;
    return 1;
}
int read_memory(struct memory *t)
{
    if( 3 != scanf("%100s %d %d", &(t->type), &(t->count), &(t->bytes)) )
	return 0;
    return 1;
}

int compare_times(const void *a, const void *b)
{
    struct times *a1, *b1;
    a1 = (struct times *)a;
    b1 = (struct times *)b;
    return (a1->time < b1->time);
}

int compare_memory(const void *a, const void *b)
{
    struct memory *a1, *b1;
    a1 = (struct memory *)a;
    b1 = (struct memory *)b;
    return (a1->bytes < b1->bytes);
}

main()
{
    struct times t[1000];
    struct memory m[100];
    char s[100];
    int i,n;

    scanf("%100[^\n]\n", s);	/* Read the first line. */

    i=0;
    while( read_times(& t[i]) )
	i++;
    n = i;

    i = n-1;
    qsort( t, n,  sizeof(struct times), compare_times);

    printf("%8s %6s %30.30s %30.30s\n","time","count","callee", "caller");
    for(i=0; i< n; i++ )
    {
	printf("%8ld %6d %30.30s %30.30s\n",
	       t[i].time, t[i].count, t[i].callee, t[i].caller);
    };
    

				/* Throw out the next two lines. */
    scanf("%100[^\n]\n", s); printf("Throwing out %s\n",s);
    scanf("%100[^\n]\n", s); printf("Throwing out %s\n",s);

    i=0;
    while( read_memory(& m[i]) )
	i++;
    n = i;
    qsort( m, n,  sizeof(struct memory), compare_memory);

    printf("\n\n%10s %10s %40.40s\n","bytes","count","type");
    for(i=0; i< n; i++ )
    {
	printf("%10d %10d %40.40s\n",m[i].bytes, m[i].count, m[i].type);
    };
    
    return 0;
}
